name: Trigger auto deployment for container-app-ny4kti2vfryts

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-ny4kti2vfryts-AutoDeployTrigger-e043e284-4080-4d9a-b48d-15aae60c5f03.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPNY4KTI2VFRYTS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPNY4KTI2VFRYTS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPNY4KTI2VFRYTS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPNY4KTI2VFRYTS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPNY4KTI2VFRYTS_REGISTRY_PASSWORD }}
          containerAppName: container-app-ny4kti2vfryts
          resourceGroup: appspacesragappa9fabed1
          imageToBuild: default/container-app-ny4kti2vfryts:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


